// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBINtfX0WrBg737GZgzKOm6cltkLHDE33c',
    appId: '1:531941075856:web:0e0fdae60fa3ea8e986115',
    messagingSenderId: '531941075856',
    projectId: 'flutter-uber-clone-2943f',
    authDomain: 'flutter-uber-clone-2943f.firebaseapp.com',
    databaseURL: 'https://flutter-uber-clone-2943f-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-uber-clone-2943f.appspot.com',
    measurementId: 'G-WXN294HLJR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9bHogRQBV0opZLuGRq1NHN94YV-7V9oM',
    appId: '1:531941075856:android:fec01b45b69c782d986115',
    messagingSenderId: '531941075856',
    projectId: 'flutter-uber-clone-2943f',
    databaseURL: 'https://flutter-uber-clone-2943f-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-uber-clone-2943f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-8PJG8XuwHkSxLvQpzYHgpLWGHvGv2vM',
    appId: '1:531941075856:ios:577a8542b1eac39d986115',
    messagingSenderId: '531941075856',
    projectId: 'flutter-uber-clone-2943f',
    databaseURL: 'https://flutter-uber-clone-2943f-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-uber-clone-2943f.appspot.com',
    androidClientId: '531941075856-ssl4ukg8giq7kibisciol75oldqnnvp6.apps.googleusercontent.com',
    iosBundleId: 'com.app.restaurant',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-8PJG8XuwHkSxLvQpzYHgpLWGHvGv2vM',
    appId: '1:531941075856:ios:577a8542b1eac39d986115',
    messagingSenderId: '531941075856',
    projectId: 'flutter-uber-clone-2943f',
    databaseURL: 'https://flutter-uber-clone-2943f-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-uber-clone-2943f.appspot.com',
    androidClientId: '531941075856-ssl4ukg8giq7kibisciol75oldqnnvp6.apps.googleusercontent.com',
    iosBundleId: 'com.app.restaurant',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZTduEAxtlNsKBVz3OLyr3tu3tEcRnfV0',
    appId: '1:531941075856:web:bbb4ce57e7d586b2986115',
    messagingSenderId: '531941075856',
    projectId: 'flutter-uber-clone-2943f',
    authDomain: 'flutter-uber-clone-2943f.firebaseapp.com',
    databaseURL: 'https://flutter-uber-clone-2943f-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-uber-clone-2943f.appspot.com',
    measurementId: 'G-H2QR5ZNFEP',
  );
}
